version: 1
update_configs:
  - package_manager: "python"
    directory: "/"
    update_schedule: "daily"
    default_assignees:
      - "bryanforbes"
    allowed_updates:
      - match:
          dependency_type: "direct"
          update_type: "all"
      - match:
          dependency_type: "indirect"
          update_type: "security"
